#theme: jekyll-theme-cayman
#title: Kang Chao' Homepage

markdown: kramdown

highlighter: rouge
url: https://kang-chao.github.io
exclude: ['README.md']


# collection and their defaults

collections:
  front-pages:
    output: true
  modules-intro:
    output: true
  loop-description:
    output: false
  tutorials:
    output: true
    permalink: /:collection/:path/
  table-contents:
    output: true
    permalink: /tutorials/:path/


defaults:
  - scope:
      path: "_front-pages"
    values:
      layout: front-page
      enable_ads: true

  - scope:
      path: "_modules-intro"
    values:
      layout: front-page

  - scope:
      path: "_table-contents"
    values:
      layout: table-of-contents

  - scope:
      path: "_tutorials"
    values:
      layout: tutorial-post
      editor: 亢超
      author: 亢超
      author-link: "#"
      enable_ads: true
      published: true  #TOD: change back to true
